//
//  Messages.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.18
//

import Foundation
import UIKit
import AWSDynamoDB



class ConversationDBModel: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _conversationId: String?
    var _content: String?
    var _messageId: String?
    var _timestamp: NSNumber?
    
    class func dynamoDBTableName() -> String {
        return "connected-mobilehub-2025034993-Messages"
    }
    
    class func hashKeyAttribute() -> String {
        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {
        return "_conversationId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_conversationId" : "conversationId",
               "_content" : "content",
               "_messageId" : "messageId",
               "_timestamp" : "timestamp",
        ]
    }
}
